# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/mainUI.ui'
#
# Created: Wed Jul 20 14:04:20 2016
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_guiDlg(object):
    def setupUi(self, guiDlg):
        guiDlg.setObjectName("guiDlg")
        guiDlg.resize(697, 518)
        self.layoutWidget = QtGui.QWidget(guiDlg)
        self.layoutWidget.setGeometry(QtCore.QRect(70, 70, 551, 383))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.progressBar_1 = QtGui.QProgressBar(self.layoutWidget)
        self.progressBar_1.setProperty("value", 24)
        self.progressBar_1.setOrientation(QtCore.Qt.Vertical)
        self.progressBar_1.setObjectName("progressBar_1")
        self.gridLayout.addWidget(self.progressBar_1, 1, 0, 1, 1)
        self.progressBar_2 = QtGui.QProgressBar(self.layoutWidget)
        self.progressBar_2.setProperty("value", 24)
        self.progressBar_2.setOrientation(QtCore.Qt.Vertical)
        self.progressBar_2.setObjectName("progressBar_2")
        self.gridLayout.addWidget(self.progressBar_2, 1, 2, 1, 1)
        self.label_1 = QtGui.QLabel(self.layoutWidget)
        self.label_1.setObjectName("label_1")
        self.gridLayout.addWidget(self.label_1, 0, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 2, 1, 1)
        self.progressBar_3 = QtGui.QProgressBar(self.layoutWidget)
        self.progressBar_3.setProperty("value", 24)
        self.progressBar_3.setOrientation(QtCore.Qt.Vertical)
        self.progressBar_3.setObjectName("progressBar_3")
        self.gridLayout.addWidget(self.progressBar_3, 1, 3, 1, 1)
        self.label_5 = QtGui.QLabel(self.layoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 5, 1, 1)
        self.label_4 = QtGui.QLabel(self.layoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 4, 1, 1)
        self.label_3 = QtGui.QLabel(self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 3, 1, 1)
        self.label_6 = QtGui.QLabel(self.layoutWidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 0, 6, 1, 1)
        self.progressBar_4 = QtGui.QProgressBar(self.layoutWidget)
        self.progressBar_4.setProperty("value", 24)
        self.progressBar_4.setOrientation(QtCore.Qt.Vertical)
        self.progressBar_4.setObjectName("progressBar_4")
        self.gridLayout.addWidget(self.progressBar_4, 1, 4, 1, 1)
        self.progressBar_5 = QtGui.QProgressBar(self.layoutWidget)
        self.progressBar_5.setProperty("value", 24)
        self.progressBar_5.setOrientation(QtCore.Qt.Vertical)
        self.progressBar_5.setObjectName("progressBar_5")
        self.gridLayout.addWidget(self.progressBar_5, 1, 5, 1, 1)
        self.progressBar_6 = QtGui.QProgressBar(self.layoutWidget)
        self.progressBar_6.setProperty("value", 24)
        self.progressBar_6.setOrientation(QtCore.Qt.Vertical)
        self.progressBar_6.setObjectName("progressBar_6")
        self.gridLayout.addWidget(self.progressBar_6, 1, 6, 1, 1)
        self.horizontalLayout_3.addLayout(self.gridLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_24 = QtGui.QLabel(self.layoutWidget)
        self.label_24.setObjectName("label_24")
        self.verticalLayout_2.addWidget(self.label_24)
        self.label_25 = QtGui.QLabel(self.layoutWidget)
        self.label_25.setObjectName("label_25")
        self.verticalLayout_2.addWidget(self.label_25)
        self.label_26 = QtGui.QLabel(self.layoutWidget)
        self.label_26.setObjectName("label_26")
        self.verticalLayout_2.addWidget(self.label_26)
        self.label_27 = QtGui.QLabel(self.layoutWidget)
        self.label_27.setObjectName("label_27")
        self.verticalLayout_2.addWidget(self.label_27)
        self.label_28 = QtGui.QLabel(self.layoutWidget)
        self.label_28.setObjectName("label_28")
        self.verticalLayout_2.addWidget(self.label_28)
        self.label_29 = QtGui.QLabel(self.layoutWidget)
        self.label_29.setObjectName("label_29")
        self.verticalLayout_2.addWidget(self.label_29)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.gridLayout_8 = QtGui.QGridLayout()
        self.gridLayout_8.setObjectName("gridLayout_8")
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_8.addItem(spacerItem1, 3, 0, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_8.addItem(spacerItem2, 5, 0, 1, 1)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.lcdNumber_4 = QtGui.QLCDNumber(self.layoutWidget)
        self.lcdNumber_4.setObjectName("lcdNumber_4")
        self.gridLayout_3.addWidget(self.lcdNumber_4, 1, 1, 1, 1)
        self.label_9 = QtGui.QLabel(self.layoutWidget)
        self.label_9.setObjectName("label_9")
        self.gridLayout_3.addWidget(self.label_9, 0, 1, 1, 1)
        self.lcdNumber_6 = QtGui.QLCDNumber(self.layoutWidget)
        self.lcdNumber_6.setObjectName("lcdNumber_6")
        self.gridLayout_3.addWidget(self.lcdNumber_6, 1, 2, 1, 1)
        self.label_10 = QtGui.QLabel(self.layoutWidget)
        self.label_10.setObjectName("label_10")
        self.gridLayout_3.addWidget(self.label_10, 0, 2, 1, 1)
        self.label_11 = QtGui.QLabel(self.layoutWidget)
        self.label_11.setObjectName("label_11")
        self.gridLayout_3.addWidget(self.label_11, 0, 0, 1, 1)
        self.lcdNumber_2 = QtGui.QLCDNumber(self.layoutWidget)
        self.lcdNumber_2.setObjectName("lcdNumber_2")
        self.gridLayout_3.addWidget(self.lcdNumber_2, 1, 0, 1, 1)
        self.gridLayout_8.addLayout(self.gridLayout_3, 2, 0, 1, 1)
        self.gridLayout_5 = QtGui.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_15 = QtGui.QLabel(self.layoutWidget)
        self.label_15.setObjectName("label_15")
        self.gridLayout_5.addWidget(self.label_15, 0, 0, 1, 1)
        self.label_16 = QtGui.QLabel(self.layoutWidget)
        self.label_16.setObjectName("label_16")
        self.gridLayout_5.addWidget(self.label_16, 0, 1, 1, 1)
        self.lcdNumber_8 = QtGui.QLCDNumber(self.layoutWidget)
        self.lcdNumber_8.setObjectName("lcdNumber_8")
        self.gridLayout_5.addWidget(self.lcdNumber_8, 1, 0, 1, 1)
        self.lcdNumber_10 = QtGui.QLCDNumber(self.layoutWidget)
        self.lcdNumber_10.setObjectName("lcdNumber_10")
        self.gridLayout_5.addWidget(self.lcdNumber_10, 1, 1, 1, 1)
        self.lcdNumber_12 = QtGui.QLCDNumber(self.layoutWidget)
        self.lcdNumber_12.setObjectName("lcdNumber_12")
        self.gridLayout_5.addWidget(self.lcdNumber_12, 1, 2, 1, 1)
        self.label_17 = QtGui.QLabel(self.layoutWidget)
        self.label_17.setObjectName("label_17")
        self.gridLayout_5.addWidget(self.label_17, 0, 2, 1, 1)
        self.gridLayout_8.addLayout(self.gridLayout_5, 6, 0, 1, 1)
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.lcdNumber_7 = QtGui.QLCDNumber(self.layoutWidget)
        self.lcdNumber_7.setObjectName("lcdNumber_7")
        self.gridLayout_4.addWidget(self.lcdNumber_7, 1, 0, 1, 1)
        self.lcdNumber_11 = QtGui.QLCDNumber(self.layoutWidget)
        self.lcdNumber_11.setObjectName("lcdNumber_11")
        self.gridLayout_4.addWidget(self.lcdNumber_11, 1, 2, 1, 1)
        self.lcdNumber_9 = QtGui.QLCDNumber(self.layoutWidget)
        self.lcdNumber_9.setObjectName("lcdNumber_9")
        self.gridLayout_4.addWidget(self.lcdNumber_9, 1, 1, 1, 1)
        self.label_12 = QtGui.QLabel(self.layoutWidget)
        self.label_12.setObjectName("label_12")
        self.gridLayout_4.addWidget(self.label_12, 0, 0, 1, 1)
        self.label_14 = QtGui.QLabel(self.layoutWidget)
        self.label_14.setObjectName("label_14")
        self.gridLayout_4.addWidget(self.label_14, 0, 1, 1, 1)
        self.label_13 = QtGui.QLabel(self.layoutWidget)
        self.label_13.setObjectName("label_13")
        self.gridLayout_4.addWidget(self.label_13, 0, 2, 1, 1)
        self.gridLayout_8.addLayout(self.gridLayout_4, 4, 0, 1, 1)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtGui.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 1, 1, 1)
        self.label_8 = QtGui.QLabel(self.layoutWidget)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 0, 2, 1, 1)
        self.lcdNumber_3 = QtGui.QLCDNumber(self.layoutWidget)
        self.lcdNumber_3.setObjectName("lcdNumber_3")
        self.gridLayout_2.addWidget(self.lcdNumber_3, 1, 1, 1, 1)
        self.lcdNumber_1 = QtGui.QLCDNumber(self.layoutWidget)
        self.lcdNumber_1.setObjectName("lcdNumber_1")
        self.gridLayout_2.addWidget(self.lcdNumber_1, 1, 0, 1, 1)
        self.lcdNumber_5 = QtGui.QLCDNumber(self.layoutWidget)
        self.lcdNumber_5.setObjectName("lcdNumber_5")
        self.gridLayout_2.addWidget(self.lcdNumber_5, 1, 2, 1, 1)
        self.label_7 = QtGui.QLabel(self.layoutWidget)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 0, 0, 1, 1)
        self.gridLayout_8.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        self.gridLayout_6 = QtGui.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.lcdNumber_13 = QtGui.QLCDNumber(self.layoutWidget)
        self.lcdNumber_13.setObjectName("lcdNumber_13")
        self.gridLayout_6.addWidget(self.lcdNumber_13, 1, 0, 1, 1)
        self.lcdNumber_17 = QtGui.QLCDNumber(self.layoutWidget)
        self.lcdNumber_17.setObjectName("lcdNumber_17")
        self.gridLayout_6.addWidget(self.lcdNumber_17, 1, 2, 1, 1)
        self.lcdNumber_15 = QtGui.QLCDNumber(self.layoutWidget)
        self.lcdNumber_15.setObjectName("lcdNumber_15")
        self.gridLayout_6.addWidget(self.lcdNumber_15, 1, 1, 1, 1)
        self.label_18 = QtGui.QLabel(self.layoutWidget)
        self.label_18.setObjectName("label_18")
        self.gridLayout_6.addWidget(self.label_18, 0, 0, 1, 1)
        self.label_19 = QtGui.QLabel(self.layoutWidget)
        self.label_19.setObjectName("label_19")
        self.gridLayout_6.addWidget(self.label_19, 0, 1, 1, 1)
        self.label_20 = QtGui.QLabel(self.layoutWidget)
        self.label_20.setObjectName("label_20")
        self.gridLayout_6.addWidget(self.label_20, 0, 2, 1, 1)
        self.gridLayout_8.addLayout(self.gridLayout_6, 8, 0, 1, 1)
        self.gridLayout_7 = QtGui.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.lcdNumber_16 = QtGui.QLCDNumber(self.layoutWidget)
        self.lcdNumber_16.setObjectName("lcdNumber_16")
        self.gridLayout_7.addWidget(self.lcdNumber_16, 1, 1, 1, 1)
        self.lcdNumber_18 = QtGui.QLCDNumber(self.layoutWidget)
        self.lcdNumber_18.setObjectName("lcdNumber_18")
        self.gridLayout_7.addWidget(self.lcdNumber_18, 1, 2, 1, 1)
        self.lcdNumber_14 = QtGui.QLCDNumber(self.layoutWidget)
        self.lcdNumber_14.setObjectName("lcdNumber_14")
        self.gridLayout_7.addWidget(self.lcdNumber_14, 1, 0, 1, 1)
        self.label_21 = QtGui.QLabel(self.layoutWidget)
        self.label_21.setObjectName("label_21")
        self.gridLayout_7.addWidget(self.label_21, 0, 0, 1, 1)
        self.label_22 = QtGui.QLabel(self.layoutWidget)
        self.label_22.setObjectName("label_22")
        self.gridLayout_7.addWidget(self.label_22, 0, 1, 1, 1)
        self.label_23 = QtGui.QLabel(self.layoutWidget)
        self.label_23.setObjectName("label_23")
        self.gridLayout_7.addWidget(self.label_23, 0, 2, 1, 1)
        self.gridLayout_8.addLayout(self.gridLayout_7, 10, 0, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_8.addItem(spacerItem3, 1, 0, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_8.addItem(spacerItem4, 7, 0, 1, 1)
        spacerItem5 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_8.addItem(spacerItem5, 9, 0, 1, 1)
        self.horizontalLayout_2.addLayout(self.gridLayout_8)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_2)
        self.layoutWidget1 = QtGui.QWidget(guiDlg)
        self.layoutWidget1.setGeometry(QtCore.QRect(130, 30, 441, 22))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_30 = QtGui.QLabel(self.layoutWidget1)
        self.label_30.setObjectName("label_30")
        self.horizontalLayout_4.addWidget(self.label_30)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem6)
        self.label_31 = QtGui.QLabel(self.layoutWidget1)
        self.label_31.setObjectName("label_31")
        self.horizontalLayout_4.addWidget(self.label_31)

        self.retranslateUi(guiDlg)
        QtCore.QMetaObject.connectSlotsByName(guiDlg)

    def retranslateUi(self, guiDlg):
        guiDlg.setWindowTitle(QtGui.QApplication.translate("guiDlg", "showSensorHexapod", None, QtGui.QApplication.UnicodeUTF8))
        self.progressBar_1.setFormat(QtGui.QApplication.translate("guiDlg", "%p", None, QtGui.QApplication.UnicodeUTF8))
        self.progressBar_2.setFormat(QtGui.QApplication.translate("guiDlg", "%p", None, QtGui.QApplication.UnicodeUTF8))
        self.label_1.setText(QtGui.QApplication.translate("guiDlg", "<html><head/><body><p align=\"center\">1</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("guiDlg", "<html><head/><body><p align=\"center\">2</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.progressBar_3.setFormat(QtGui.QApplication.translate("guiDlg", "%p", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("guiDlg", "<html><head/><body><p align=\"center\">5</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("guiDlg", "<html><head/><body><p align=\"center\">4</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("guiDlg", "<html><head/><body><p align=\"center\">3</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("guiDlg", "<html><head/><body><p align=\"center\">6</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.progressBar_4.setFormat(QtGui.QApplication.translate("guiDlg", "%p", None, QtGui.QApplication.UnicodeUTF8))
        self.progressBar_5.setFormat(QtGui.QApplication.translate("guiDlg", "%p", None, QtGui.QApplication.UnicodeUTF8))
        self.progressBar_6.setFormat(QtGui.QApplication.translate("guiDlg", "%p", None, QtGui.QApplication.UnicodeUTF8))
        self.label_24.setText(QtGui.QApplication.translate("guiDlg", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_25.setText(QtGui.QApplication.translate("guiDlg", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.label_26.setText(QtGui.QApplication.translate("guiDlg", "3", None, QtGui.QApplication.UnicodeUTF8))
        self.label_27.setText(QtGui.QApplication.translate("guiDlg", "4", None, QtGui.QApplication.UnicodeUTF8))
        self.label_28.setText(QtGui.QApplication.translate("guiDlg", "5", None, QtGui.QApplication.UnicodeUTF8))
        self.label_29.setText(QtGui.QApplication.translate("guiDlg", "6", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("guiDlg", "4", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("guiDlg", "6", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("guiDlg", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("guiDlg", "8", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("guiDlg", "10", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("guiDlg", "12", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("guiDlg", "7", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("guiDlg", "9", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("guiDlg", "11", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("guiDlg", "3", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("guiDlg", "5", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("guiDlg", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("guiDlg", "13", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("guiDlg", "15", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("guiDlg", "17", None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setText(QtGui.QApplication.translate("guiDlg", "14", None, QtGui.QApplication.UnicodeUTF8))
        self.label_22.setText(QtGui.QApplication.translate("guiDlg", "16", None, QtGui.QApplication.UnicodeUTF8))
        self.label_23.setText(QtGui.QApplication.translate("guiDlg", "18", None, QtGui.QApplication.UnicodeUTF8))
        self.label_30.setText(QtGui.QApplication.translate("guiDlg", "Presión", None, QtGui.QApplication.UnicodeUTF8))
        self.label_31.setText(QtGui.QApplication.translate("guiDlg", "Temperatura", None, QtGui.QApplication.UnicodeUTF8))

